#ifndef MACROS_H_
#define MACROS_H_

#define RCC_AHB1ENREG_ADDR ((0x40023800) + (0x30))
#define GPIOD_MODEREG_ADDR (0x40020C00)
#define GPIOD_IDREG_ADDR ((0x40020C00) + (0x10))
#define GPIOD_ODREG_ADDR ((0x40020C00) + (0x14))
#define GPIOD_PUPDREG_ADDR ((0x40020C00) + (0x0C))
#define CASUAL_MODE ('1')
#define CASUAL_MODE_SEQ_LEN (2)
#define CASUAL_MODE_LIVES (3)
#define PRO_MODE ('2')
#define PRO_MODE_SEQ_LEN (4)
#define PRO_MODE_LIVES (1)
#define GAME_CONFIG_MAX_SEQ_LEN (99)
#define GAME_CONFIG_SCORE (0)
#define GAME_CONFIG_STAGE (0)
#define KEYPAD_1 ('1')
#define KEYPAD_2 ('2')
#define KEYPAD_3 ('3')
#define KEYPAD_4 ('4')
#define KEYPAD_5 ('5')
#define KEYPAD_6 ('6')
#define KEYPAD_7 ('7')
#define KEYPAD_8 ('8')
#define KEYPAD_9 ('9')
#define KEYPAD_0 ('0')
#define KEYPAD_A ('A')
#define KEYPAD_B ('B')
#define KEYPAD_C ('C')
#define KEYPAD_D ('D')
#define KEYPAD_STAR ('*')
#define KEYPAD_HASH ('#')

#endif
